In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import requests
import json

In this exercise, you'll redo the data gathering phase of the UNData Exploration project by using APIs instead of downloading csv files.

You'll make use of the [World Bank Indicators API](https://datahelpdesk.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api-documentation). 
Note that this API does not require an API key. Before attempting the exercise, it would be a good idea to skim through the Documentation page and to check out the 
[Basic Call Structure article](https://datahelpdesk.worldbank.org/knowledgebase/articles/898581).

1. Use the API to get all available data for the _GDP per capita, PPP (constant 2017 international $)_ indicator. Hint: this indicator has code "NY.GDP.PCAP.PP.KD".
Adjust the query parameters so that you can retrieve all available rows. Convert the results to a DataFrame.

In [2]:
endpoint = 'https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.PP.KD'

In [3]:
params = {
    'format': 'json',
    'per_page': '20000'
}
response = requests.get(endpoint,params = params)
response

In [4]:
res = response.json()
res

[{'page': 1,
  'pages': 1,
  'per_page': 20000,
  'total': 17490,
  'sourceid': '2',
  'lastupdated': '2026-07-01'},
 [{'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2025',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2024',
   'value': 4106.43414035047,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2023',
   'value': 4083.99300263507,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2022',
   'value': 4106.50190693219,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2021',
   'value': 4056.11301700129,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2020',
   'value': 3978.93139450095,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2019',
   'value': 4195.86541780344,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2018',
   'value': 4220.91250168849,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2017',
   'value': 4214.39708524398,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2016',
   'value': 4202.23641584707,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2015',
   'value': 4206.25295270438,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2014',
   'value': 4185.23841104229,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2013',
   'value': 4125.18256263035,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2012',
   'value': 4061.64163525859,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2011',
   'value': 4042.84247175787,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2010',
   'value': 3976.01098918458,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2009',
   'value': 3869.99812557719,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2008',
   'value': 3934.08423728651,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2007',
   'value': 3866.72395287147,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2006',
   'value': 3718.02241324132,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2005',
   'value': 3577.58589657798,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2004',
   'value': 3457.12022216505,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2003',
   'value': 3357.24486194198,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2002',
   'value': 3350.14106469179,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2001',
   'value': 3313.42192907347,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2000',
   'value': 3281.92231355821,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1999',
   'value': 3267.96274823069,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1998',
   'value': 3269.06995117859,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1997',
   'value': 3291.25656501965,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1996',
   'value': 3246.82586499728,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1995',
   'value': 3154.79090002396,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1994',
   'value': 3099.31243976356,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1993',
   'value': 3127.2935723296,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1992',
   'value': 3251.64780568922,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1991',
   'value': 3424.50025403354,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1990',
   'value': 3519.3175448125,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1989',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1988',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1987',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1986',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1985',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1984',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1983',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1982',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1981',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1980',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1979',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1978',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1977',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1976',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1975',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1974',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1973',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1972',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1971',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1970',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1969',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1968',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1967',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1966',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1965',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1964',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1963',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1962',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
    'value': 'GDP per capita, PPP (constant 2021 international $)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},

In [5]:
res[1]

[{'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2025',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2024',
  'value': 4106.43414035047,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2023',
  'value': 4083.99300263507,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2022',
  'value': 4106.50190693219,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2021',
  'value': 4056.11301700129,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2020',
  'value': 3978.93139450095,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2019',
  'value': 4195.86541780344,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2018',
  'value': 4220.91250168849,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2017',
  'value': 4214.39708524398,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2016',
  'value': 4202.23641584707,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2015',
  'value': 4206.25295270438,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2014',
  'value': 4185.23841104229,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2013',
  'value': 4125.18256263035,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2012',
  'value': 4061.64163525859,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2011',
  'value': 4042.84247175787,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2010',
  'value': 3976.01098918458,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2009',
  'value': 3869.99812557719,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2008',
  'value': 3934.08423728651,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2007',
  'value': 3866.72395287147,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2006',
  'value': 3718.02241324132,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2005',
  'value': 3577.58589657798,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2004',
  'value': 3457.12022216505,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2003',
  'value': 3357.24486194198,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2002',
  'value': 3350.14106469179,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2001',
  'value': 3313.42192907347,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2000',
  'value': 3281.92231355821,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1999',
  'value': 3267.96274823069,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1998',
  'value': 3269.06995117859,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1997',
  'value': 3291.25656501965,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1996',
  'value': 3246.82586499728,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1995',
  'value': 3154.79090002396,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1994',
  'value': 3099.31243976356,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1993',
  'value': 3127.2935723296,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1992',
  'value': 3251.64780568922,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1991',
  'value': 3424.50025403354,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1990',
  'value': 3519.3175448125,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1989',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1988',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1987',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1986',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1985',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1984',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1983',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1982',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1981',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1980',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1979',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1978',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1977',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1976',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1975',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1974',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1973',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1972',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1971',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1970',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1969',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1968',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1967',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1966',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1965',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1964',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1963',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1962',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1961',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '1960',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},
 {'indicator': {'id': 'NY.GDP.PCAP.PP.KD',
   'value': 'GDP per capita, PPP (constant 2021 international $)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2025',
  'value': None,
  'unit': '',
  'obs_status': '',
  'decimal': 0},

In [6]:
gdp_per_capita = pd.json_normalize(res[1])
gdp_per_capita.head()

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,AFE,2025,NaN,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
1,AFE,2024,4106.434140,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
2,AFE,2023,4083.993003,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
3,AFE,2022,4106.501907,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
4,AFE,2021,4056.113017,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern

In [7]:
gdp_per_capita.columns

Index(['countryiso3code', 'date', 'value', 'unit', 'obs_status', 'decimal',
       'indicator.id', 'indicator.value', 'country.id', 'country.value'],
      dtype='object')

In [8]:
gdp_per_capita = gdp_per_capita.drop(columns = ['countryiso3code','unit', 'obs_status', 'decimal','indicator.id', 'indicator.value', 'country.id'])
gdp_per_capita.head()

   date        value                country.value
0  2025          NaN  Africa Eastern and Southern
1  2024  4106.434140  Africa Eastern and Southern
2  2023  4083.993003  Africa Eastern and Southern
3  2022  4106.501907  Africa Eastern and Southern
4  2021  4056.113017  Africa Eastern and Southern

In [9]:
gdp_per_capita = gdp_per_capita.rename(columns = {'date': 'Year', 'value': 'GDP Per Capita', 'country.value':'Country'})
gdp_per_capita.head()

   Year  GDP Per Capita                      Country
0  2025             NaN  Africa Eastern and Southern
1  2024     4106.434140  Africa Eastern and Southern
2  2023     4083.993003  Africa Eastern and Southern
3  2022     4106.501907  Africa Eastern and Southern
4  2021     4056.113017  Africa Eastern and Southern

2. Now, use the API to get all available data for _Life expectancy at birth, total (years)_. This indicator has code "SP.DYN.LE00.IN". Again, convert the results to a DataFrame.

In [10]:
endpoint = 'https://api.worldbank.org/v2/country/all/indicator/SP.DYN.LE00.IN'

In [11]:
params = {
    'format': 'json',
    'per_page': '20000'
}
response = requests.get(endpoint,params = params)
response.json()

[{'page': 1,
  'pages': 1,
  'per_page': 20000,
  'total': 17490,
  'sourceid': '2',
  'lastupdated': '2026-07-13'},
 [{'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2025',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2024',
   'value': 65.3499304660954,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2023',
   'value': 65.1462279163724,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2022',
   'value': 64.4871517904367,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2021',
   'value': 62.9799991857494,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2020',
   'value': 63.7664840026943,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2019',
   'value': 63.8572612837043,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2018',
   'value': 63.3306913582336,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2017',
   'value': 62.5912750961501,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2016',
   'value': 62.1679813169199,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2015',
   'value': 61.713030523495,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2014',
   'value': 61.251436015671,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2013',
   'value': 60.895739752772,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2012',
   'value': 60.2495123598467,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2011',
   'value': 59.2000040300701,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2010',
   'value': 58.8272792062821,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2009',
   'value': 58.0955271436463,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2008',
   'value': 57.2401063228798,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2007',
   'value': 56.4843531784534,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2006',
   'value': 55.6935152578453,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2005',
   'value': 54.8076807136336,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2004',
   'value': 54.1929278660434,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2003',
   'value': 53.6783047685822,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2002',
   'value': 53.2067443343026,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2001',
   'value': 52.8755360536287,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2000',
   'value': 52.5573418626777,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1999',
   'value': 51.8070772449868,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1998',
   'value': 51.3179554721368,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1997',
   'value': 51.5708865171429,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1996',
   'value': 51.3531898360738,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1995',
   'value': 51.4820566813357,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1994',
   'value': 50.9665887956464,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1993',
   'value': 51.0737619133776,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1992',
   'value': 50.7159460478921,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1991',
   'value': 50.8732436063946,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1990',
   'value': 51.0963264543047,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1989',
   'value': 51.2658735140762,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1988',
   'value': 50.8766070614947,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1987',
   'value': 51.0689429320971,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1986',
   'value': 50.0097614989116,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1985',
   'value': 49.3929024640878,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1984',
   'value': 48.9979586702536,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1983',
   'value': 48.9040956565702,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1982',
   'value': 50.2908293797205,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1981',
   'value': 50.0204932967522,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1980',
   'value': 49.816713138052,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1979',
   'value': 49.4169883847351,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1978',
   'value': 48.9839167133521,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1977',
   'value': 48.8607248856663,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1976',
   'value': 48.568138198282,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1975',
   'value': 47.9685480547674,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1974',
   'value': 47.7443277639797,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1973',
   'value': 47.7466079240168,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1972',
   'value': 47.1667922827106,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1971',
   'value': 47.4640156591505,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1970',
   'value': 47.2480056807395,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1969',
   'value': 46.977475702472,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1968',
   'value': 46.7386317469603,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1967',
   'value': 46.4407454164319,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1966',
   'value': 45.7657253575752,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1965',
   'value': 45.7707229233552,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1964',
   'value': 45.5356954673738,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1963',
   'value': 45.160582805883,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1962',
   'value': 44.8778899276436,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1961',
   'value': 44.4688383362574,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1960',
   'value': 44.169658253166,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2025',
   'value': None,

In [12]:
res = response.json()

In [13]:
res

[{'page': 1,
  'pages': 1,
  'per_page': 20000,
  'total': 17490,
  'sourceid': '2',
  'lastupdated': '2026-07-13'},
 [{'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2025',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2024',
   'value': 65.3499304660954,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2023',
   'value': 65.1462279163724,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2022',
   'value': 64.4871517904367,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2021',
   'value': 62.9799991857494,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2020',
   'value': 63.7664840026943,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2019',
   'value': 63.8572612837043,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2018',
   'value': 63.3306913582336,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2017',
   'value': 62.5912750961501,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2016',
   'value': 62.1679813169199,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2015',
   'value': 61.713030523495,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2014',
   'value': 61.251436015671,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2013',
   'value': 60.895739752772,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2012',
   'value': 60.2495123598467,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2011',
   'value': 59.2000040300701,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2010',
   'value': 58.8272792062821,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2009',
   'value': 58.0955271436463,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2008',
   'value': 57.2401063228798,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2007',
   'value': 56.4843531784534,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2006',
   'value': 55.6935152578453,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2005',
   'value': 54.8076807136336,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2004',
   'value': 54.1929278660434,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2003',
   'value': 53.6783047685822,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2002',
   'value': 53.2067443343026,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2001',
   'value': 52.8755360536287,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2000',
   'value': 52.5573418626777,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1999',
   'value': 51.8070772449868,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1998',
   'value': 51.3179554721368,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1997',
   'value': 51.5708865171429,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1996',
   'value': 51.3531898360738,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1995',
   'value': 51.4820566813357,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1994',
   'value': 50.9665887956464,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1993',
   'value': 51.0737619133776,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1992',
   'value': 50.7159460478921,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1991',
   'value': 50.8732436063946,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1990',
   'value': 51.0963264543047,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1989',
   'value': 51.2658735140762,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1988',
   'value': 50.8766070614947,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1987',
   'value': 51.0689429320971,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1986',
   'value': 50.0097614989116,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1985',
   'value': 49.3929024640878,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1984',
   'value': 48.9979586702536,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1983',
   'value': 48.9040956565702,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1982',
   'value': 50.2908293797205,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1981',
   'value': 50.0204932967522,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1980',
   'value': 49.816713138052,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1979',
   'value': 49.4169883847351,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1978',
   'value': 48.9839167133521,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1977',
   'value': 48.8607248856663,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1976',
   'value': 48.568138198282,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1975',
   'value': 47.9685480547674,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1974',
   'value': 47.7443277639797,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1973',
   'value': 47.7466079240168,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1972',
   'value': 47.1667922827106,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1971',
   'value': 47.4640156591505,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1970',
   'value': 47.2480056807395,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1969',
   'value': 46.977475702472,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1968',
   'value': 46.7386317469603,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1967',
   'value': 46.4407454164319,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1966',
   'value': 45.7657253575752,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1965',
   'value': 45.7707229233552,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1964',
   'value': 45.5356954673738,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1963',
   'value': 45.160582805883,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1962',
   'value': 44.8778899276436,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1961',
   'value': 44.4688383362574,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1960',
   'value': 44.169658253166,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.DYN.LE00.IN',
    'value': 'Life expectancy at birth, total (years)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2025',
   'value': None,

In [14]:
life_expectancy = pd.json_normalize(res[1])
life_expectancy.head()

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,AFE,2025,NaN,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
1,AFE,2024,65.349930,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
2,AFE,2023,65.146228,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
3,AFE,2022,64.487152,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
4,AFE,2021,62.979999,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern

In [15]:
life_expectancy = life_expectancy.drop(columns = ['countryiso3code','unit', 'obs_status', 'decimal','indicator.id', 'indicator.value', 'country.id'])
life_expectancy.head()

   date      value                country.value
0  2025        NaN  Africa Eastern and Southern
1  2024  65.349930  Africa Eastern and Southern
2  2023  65.146228  Africa Eastern and Southern
3  2022  64.487152  Africa Eastern and Southern
4  2021  62.979999  Africa Eastern and Southern

In [16]:
life_expectancy = life_expectancy.rename(columns = {'date': 'Year', 'value': 'Life Expectancy', 'country.value':'Country'})
life_expectancy.head()

   Year  Life Expectancy                      Country
0  2025              NaN  Africa Eastern and Southern
1  2024        65.349930  Africa Eastern and Southern
2  2023        65.146228  Africa Eastern and Southern
3  2022        64.487152  Africa Eastern and Southern
4  2021        62.979999  Africa Eastern and Southern

3. Merge the two results DataFrames together. You may want to rename or drop columns prior to merging.

In [17]:
gdp_life = pd.DataFrame.merge(life_expectancy,gdp_per_capita, how = 'inner', on = ['Year','Country'])
gdp_life.head()

   Year  Life Expectancy                      Country  GDP Per Capita
0  2025              NaN  Africa Eastern and Southern             NaN
1  2024        65.349930  Africa Eastern and Southern     4106.434140
2  2023        65.146228  Africa Eastern and Southern     4083.993003
3  2022        64.487152  Africa Eastern and Southern     4106.501907
4  2021        62.979999  Africa Eastern and Southern     4056.113017

In [18]:
gdp_life = gdp_life[['Year', 'Country','Life Expectancy','GDP Per Capita']]
gdp_life.head()

   Year                      Country  Life Expectancy  GDP Per Capita
0  2025  Africa Eastern and Southern              NaN             NaN
1  2024  Africa Eastern and Southern        65.349930     4106.434140
2  2023  Africa Eastern and Southern        65.146228     4083.993003
3  2022  Africa Eastern and Southern        64.487152     4106.501907
4  2021  Africa Eastern and Southern        62.979999     4056.113017

4. You can also get more information about the available countries (region, capital city, income level classification, etc.) by using the 
[Country API](https://datahelpdesk.worldbank.org/knowledgebase/articles/898590-country-api-queries). Use this API to pull in all available data. 
Merge this with your other datasets. Use this to now remove the rows that correspond to regions and not countries.

In [19]:
endpoint = 'https://api.worldbank.org/v2/country'

In [20]:
params = {
    'format': 'json',
    'per_page': '20000'
}
response = requests.get(endpoint,params = params)
response

In [21]:
res = response.json()
res

[{'page': 1, 'pages': 1, 'per_page': '20000', 'total': 295},
 [{'id': 'ABW',
   'iso2Code': 'AW',
   'name': 'Aruba',
   'region': {'id': 'LCN',
    'iso2code': 'ZJ',
    'value': 'Latin America & Caribbean '},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
   'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
   'capitalCity': 'Oranjestad',
   'longitude': '-70.0167',
   'latitude': '12.5167'},
  {'id': 'AFE',
   'iso2Code': 'ZH',
   'name': 'Africa Eastern and Southern',
   'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
   'capitalCity': '',
   'longitude': '',
   'latitude': ''},
  {'id': 'AFG',
   'iso2Code': 'AF',
   'name': 'Afghanistan',
   'region': {'id': 'MEA',
    'iso2code': 'ZQ',
    'value': 'Middle East, North Africa, Afghanistan & Pakistan'},
   'adminregion': {'id': 'MNA',
    'iso2code': 'XQ',
    'value': 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)'},
   'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'},
   'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
   'capitalCity': 'Kabul',
   'longitude': '69.1761',
   'latitude': '34.5228'},
  {'id': 'AFR',
   'iso2Code': 'A9',
   'name': 'Africa',
   'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
   'capitalCity': '',
   'longitude': '',
   'latitude': ''},
  {'id': 'AFW',
   'iso2Code': 'ZI',
   'name': 'Africa Western and Central',
   'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
   'capitalCity': '',
   'longitude': '',
   'latitude': ''},
  {'id': 'AGO',
   'iso2Code': 'AO',
   'name': 'Angola',
   'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '},
   'adminregion': {'id': 'SSA',
    'iso2code': 'ZF',
    'value': 'Sub-Saharan Africa (excluding high income)'},
   'incomeLevel': {'id': 'LMC',
    'iso2code': 'XN',
    'value': 'Lower middle income'},
   'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
   'capitalCity': 'Luanda',
   'longitude': '13.242',
   'latitude': '-8.81155'},
  {'id': 'ALB',
   'iso2Code': 'AL',
   'name': 'Albania',
   'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
   'adminregion': {'id': 'ECA',
    'iso2code': '7E',
    'value': 'Europe & Central Asia (excluding high income)'},
   'incomeLevel': {'id': 'UMC',
    'iso2code': 'XT',
    'value': 'Upper middle income'},
   'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
   'capitalCity': 'Tirane',
   'longitude': '19.8172',
   'latitude': '41.3317'},
  {'id': 'AND',
   'iso2Code': 'AD',
   'name': 'Andorra',
   'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
   'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
   'capitalCity': 'Andorra la Vella',
   'longitude': '1.5218',
   'latitude': '42.5075'},
  {'id': 'ARB',
   'iso2Code': '1A',
   'name': 'Arab World',
   'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
   'capitalCity': '',
   'longitude': '',
   'latitude': ''},
  {'id': 'ARE',
   'iso2Code': 'AE',
   'name': 'United Arab Emirates',
   'region': {'id': 'MEA',
    'iso2code': 'ZQ',
    'value': 'Middle East, North Africa, Afghanistan & Pakistan'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
   'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
   'capitalCity': 'Abu Dhabi',
   'longitude': '54.3705',
   'latitude': '24.4764'},
  {'id': 'ARG',
   'iso2Code': 'AR',
   'name': 'Argentina',
   'region': {'id': 'LCN',
    'iso2code': 'ZJ',
    'value': 'Latin America & Caribbean '},
   'adminregion': {'id': 'LAC',
    'iso2code': 'XJ',
    'value': 'Latin America & Caribbean (excluding high income)'},
   'incomeLevel': {'id': 'UMC',
    'iso2code': 'XT',
    'value': 'Upper middle income'},
   'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
   'capitalCity': 'Buenos Aires',
   'longitude': '-58.4173',
   'latitude': '-34.6118'},
  {'id': 'ARM',
   'iso2Code': 'AM',
   'name': 'Armenia',
   'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
   'adminregion': {'id': 'ECA',
    'iso2code': '7E',
    'value': 'Europe & Central Asia (excluding high income)'},
   'incomeLevel': {'id': 'UMC',
    'iso2code': 'XT',
    'value': 'Upper middle income'},
   'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
   'capitalCity': 'Yerevan',
   'longitude': '44.509',
   'latitude': '40.1596'},
  {'id': 'ASM',
   'iso2Code': 'AS',
   'name': 'American Samoa',
   'region': {'id': 'EAS', 'iso2code': 'Z4', 'value': 'East Asia & Pacific'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
   'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
   'capitalCity': 'Pago Pago',
   'longitude': '-170.691',
   'latitude': '-14.2846'},
  {'id': 'ATG',
   'iso2Code': 'AG',
   'name': 'Antigua and Barbuda',
   'region': {'id': 'LCN',
    'iso2code': 'ZJ',
    'value': 'Latin America & Caribbean '},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
   'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
   'capitalCity': "Saint John's",
   'longitude': '-61.8456',
   'latitude': '17.1175'},
  {'id': 'AUS',
   'iso2Code': 'AU',
   'name': 'Australia',
   'region': {'id': 'EAS', 'iso2code': 'Z4', 'value': 'East Asia & Pacific'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
   'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
   'capitalCity': 'Canberra',
   'longitude': '149.129',
   'latitude': '-35.282'},
  {'id': 'AUT',
   'iso2Code': 'AT',
   'name': 'Austria',
   'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
   'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
   'capitalCity': 'Vienna',
   'longitude': '16.3798',
   'latitude': '48.2201'},
  {'id': 'AZE',
   'iso2Code': 'AZ',
   'name': 'Azerbaijan',
   'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
   'adminregion': {'id': 'ECA',
    'iso2code': '7E',
    'value': 'Europe & Central Asia (excluding high income)'},
   'incomeLevel': {'id': 'UMC',
    'iso2code': 'XT',
    'value': 'Upper middle income'},
   'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
   'capitalCity': 'Baku',
   'longitude': '49.8932',
   'latitude': '40.3834'},
  {'id': 'BDI',
   'iso2Code': 'BI',
   'name': 'Burundi',
   'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '},
   'adminregion': {'id': 'SSA',
    'iso2code': 'ZF',
    'value': 'Sub-Saharan Africa (excluding high income)'},
   'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'},
   'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
   'capitalCity': 'Bujumbura',
   'longitude': '29.3639',
   'latitude': '-3.3784'},
  {'id': 'BEA',
   'iso2Code': 'B4',
   'name': 'East Asia & Pacific (IBRD-only countries)',
   'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
   'capitalCity': '',
   'longitude': '',
   'latitude': ''},
  {'id': 'BEC',
   'iso2Code': 'B7',
   'name': 'Europe & Central Asia (IBRD-only countries)',
   'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
   'capitalCity': '',
   'longitude': '',
   'latitude': ''},
  {'id': 'BEL',
   'iso2Code': 'BE',
   'name': 'Belgium',
   'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
   'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
   'capitalCity': 'Brussels',
   'longitude': '4.36761',
   'latitude': '50.8371'},
  {'id': 'BEN',
   'iso2Code': 'BJ',
   'name': 'Benin',
   'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '},
   'adminregion': {'id': 'SSA',
    'iso2code': 'ZF',
    'value': 'Sub-Saharan Africa (excluding high income)'},
   'incomeLevel': {'id': 'LMC',
    'iso2code': 'XN',
    'value': 'Lower middle income'},
   'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
   'capitalCity': 'Porto-Novo',
   'longitude': '2.6323',
   'latitude': '6.4779'},
  {'id': 'BFA',
   'iso2Code': 'BF',
   'name': 'Burkina Faso',
   'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '},
   'adminregion': {'id': 'SSA',
    'iso2code': 'ZF',
    'value': 'Sub-Saharan Africa (excluding high income)'},
   'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'},
   'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
   'capitalCity': 'Ouagadougou',
   'longitude': '-1.53395',
   'latitude': '12.3605'},
  {'id': 'BGD',
   'iso2Code': 'BD',
   'name': 'Bangladesh',
   'region': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'},
   'adminregion': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'},
   'incomeLevel': {'id': 'LMC',
    'iso2code': 'XN',
    'value': 'Lower middle income'},
   'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
   'capitalCity': 'Dhaka',
   'longitude': '90.4113',
   'latitude': '23.7055'},
  {'id': 'BGR',
   'iso2Code': 'BG',
   'name': 'Bulgaria',
   'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
   'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
   'capitalCity': 'Sofia',
   'longitude': '23.3238',
   'latitude': '42.7105'},
  {'id': 'BHI',
   'iso2Code': 'B1',
   'name': 'IBRD countries classified as high income',
   'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
   'capitalCity': '',
   'longitude': '',
   'latitude': ''},
  {'id': 'BHR',
   'iso2Code': 'BH',
   'name': 'Bahrain',
   'region': {'id': 'MEA',
    'iso2code': 'ZQ',
    'value': 'Middle East, North Africa, Afghanistan & Pakistan'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
   'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
   'capitalCity': 'Manama',
   'longitude': '50.5354',
   'latitude': '26.1921'},
  {'id': 'BHS',
   'iso2Code': 'BS',
   'name': 'Bahamas, The',
   'region': {'id': 'LCN',
    'iso2code': 'ZJ',
    'value': 'Latin America & Caribbean '},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
   'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
   'capitalCity': 'Nassau',
   'longitude': '-77.339',
   'latitude': '25.0661'},
  {'id': 'BIH',
   'iso2Code': 'BA',
   'name': 'Bosnia and Herzegovina',
   'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
   'adminregion': {'id': 'ECA',
    'iso2code': '7E',
    'value': 'Europe & Central Asia (excluding high income)'},
   'incomeLevel': {'id': 'UMC',
    'iso2code': 'XT',
    'value': 'Upper middle income'},
   'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
   'capitalCity': 'Sarajevo',
   'longitude': '18.4214',
   'latitude': '43.8607'},
  {'id': 'BLA',
   'iso2Code': 'B2',
   'name': 'Latin America & the Caribbean (IBRD-only countries)',
   'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
   'capitalCity': '',
   'longitude': '',
   'latitude': ''},
  {'id': 'BLR',
   'iso2Code': 'BY',
   'name': 'Belarus',
   'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'},
   'adminregion': {'id': 'ECA',
    'iso2code': '7E',
    'value': 'Europe & Central Asia (excluding high income)'},
   'incomeLevel': {'id': 'UMC',
    'iso2code': 'XT',
    'value': 'Upper middle income'},
   'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
   'capitalCity': 'Minsk',
   'longitude': '27.5766',
   'latitude': '53.9678'},
  {'id': 'BLZ',
   'iso2Code': 'BZ',
   'name': 'Belize',
   'region': {'id': 'LCN',
    'iso2code': 'ZJ',
    'value': 'Latin America & Caribbean '},
   'adminregion': {'id': 'LAC',
    'iso2code': 'XJ',
    'value': 'Latin America & Caribbean (excluding high income)'},
   'incomeLevel': {'id': 'UMC',
    'iso2code': 'XT',
    'value': 'Upper middle income'},
   'lendingType': {'id': 'IDB', 'iso2code': 'XH', 'value': 'Blend'},
   'capitalCity': 'Belmopan',
   'longitude': '-88.7713',
   'latitude': '17.2534'},
  {'id': 'BMN',
   'iso2Code': 'B3',
   'name': 'Middle East, North Africa, Afghanistan & Pakistan (IBRD only)',
   'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
   'capitalCity': '',
   'longitude': '',
   'latitude': ''},
  {'id': 'BMU',
   'iso2Code': 'BM',
   'name': 'Bermuda',
   'region': {'id': 'NAC', 'iso2code': 'XU', 'value': 'North America'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
   'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
   'capitalCity': 'Hamilton',
   'longitude': '-64.706',
   'latitude': '32.3293'},
  {'id': 'BOL',
   'iso2Code': 'BO',
   'name': 'Bolivia',
   'region': {'id': 'LCN',
    'iso2code': 'ZJ',
    'value': 'Latin America & Caribbean '},
   'adminregion': {'id': 'LAC',
    'iso2code': 'XJ',
    'value': 'Latin America & Caribbean (excluding high income)'},
   'incomeLevel': {'id': 'LMC',
    'iso2code': 'XN',
    'value': 'Lower middle income'},
   'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
   'capitalCity': 'La Paz',
   'longitude': '-66.1936',
   'latitude': '-13.9908'},
  {'id': 'BRA',
   'iso2Code': 'BR',
   'name': 'Brazil',
   'region': {'id': 'LCN',
    'iso2code': 'ZJ',
    'value': 'Latin America & Caribbean '},
   'adminregion': {'id': 'LAC',
    'iso2code': 'XJ',
    'value': 'Latin America & Caribbean (excluding high income)'},
   'incomeLevel': {'id': 'UMC',
    'iso2code': 'XT',
    'value': 'Upper middle income'},
   'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
   'capitalCity': 'Brasilia',
   'longitude': '-47.9292',
   'latitude': '-15.7801'},
  {'id': 'BRB',
   'iso2Code': 'BB',
   'name': 'Barbados',
   'region': {'id': 'LCN',
    'iso2code': 'ZJ',
    'value': 'Latin America & Caribbean '},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
   'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
   'capitalCity': 'Bridgetown',
   'longitude': '-59.6105',
   'latitude': '13.0935'},
  {'id': 'BRN',
   'iso2Code': 'BN',
   'name': 'Brunei Darussalam',
   'region': {'id': 'EAS', 'iso2code': 'Z4', 'value': 'East Asia & Pacific'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
   'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
   'capitalCity': 'Bandar Seri Begawan',
   'longitude': '114.946',
   'latitude': '4.94199'},
  {'id': 'BSS',
   'iso2Code': 'B6',
   'name': 'Sub-Saharan Africa (IBRD-only countries)',
   'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
   'capitalCity': '',
   'longitude': '',
   'latitude': ''},
  {'id': 'BTN',
   'iso2Code': 'BT',
   'name': 'Bhutan',
   'region': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'},
   'adminregion': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'},
   'incomeLevel': {'id': 'LMC',
    'iso2code': 'XN',
    'value': 'Lower middle income'},
   'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
   'capitalCity': 'Thimphu',
   'longitude': '89.6177',
   'latitude': '27.5768'},
  {'id': 'BWA',
   'iso2Code': 'BW',
   'name': 'Botswana',
   'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '},
   'adminregion': {'id': 'SSA',
    'iso2code': 'ZF',
    'value': 'Sub-Saharan Africa (excluding high income)'},
   'incomeLevel': {'id': 'UMC',
    'iso2code': 'XT',
    'value': 'Upper middle income'},
   'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
   'capitalCity': 'Gaborone',
   'longitude': '25.9201',
   'latitude': '-24.6544'},
  {'id': 'CAA',
   'iso2Code': 'C9',
   'name': 'Sub-Saharan Africa (IFC classification)',
   'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'adminregion': {'id': '', 'iso2code': '', 'value': ''},
   'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
   'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
   'capitalCity': '',
   'longitude': '',
   'latitude': ''},
  {'id': 'CAF',
   'iso2Code': 'CF',
   'name': 'Central African Republic',
   'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '},
   'adminregion': {'id': 'SSA',
    'iso2code': 'ZF',
    'value': 'Sub-Saharan Africa (excluding high income)'},
   'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'},
   'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
   'capitalCity': 'Bangui',
   'longitude': '21.6407',
   'latitude': '5.63056'},
  {'id': 'CAN',
   'iso2Code': 'CA',
   'name': 'Canada',
   'region': {'id': 'NAC', 'iso2code': 'XU', 'value': 'North America'},

In [22]:
country_classification = pd.json_normalize(res[1])
country_classification.head()

,id,iso2Code,name,capitalCity,longitude,latitude,region.id,region.iso2code,region.value,adminregion.id,adminregion.iso2code,adminregion.value,incomeLevel.id,incomeLevel.iso2code,incomeLevel.value,lendingType.id,lendingType.iso2code,lendingType.value
0,ABW,AW,Aruba,Oranjestad,-70.0167,12.5167,LCN,ZJ,Latin America & Caribbean,,,,HIC,XD,High income,LNX,XX,Not classified
1,AFE,ZH,Africa Eastern and Southern,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
2,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,MEA,ZQ,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
3,AFR,A9,Africa,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
4,AFW,ZI,Africa Western and Central,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates

In [23]:
country_classification.columns

Index(['id', 'iso2Code', 'name', 'capitalCity', 'longitude', 'latitude',
       'region.id', 'region.iso2code', 'region.value', 'adminregion.id',
       'adminregion.iso2code', 'adminregion.value', 'incomeLevel.id',
       'incomeLevel.iso2code', 'incomeLevel.value', 'lendingType.id',
       'lendingType.iso2code', 'lendingType.value'],
      dtype='object')

In [24]:
gdp_life.columns

Index(['Year', 'Country', 'Life Expectancy', 'GDP Per Capita'], dtype='object')

In [25]:
country_gdp_life = pd.DataFrame.merge(gdp_life, country_classification, how = 'outer', right_on = 'name', left_on = 'Country') 
country_gdp_life

,Year,Country,Life Expectancy,GDP Per Capita,id,iso2Code,name,capitalCity,longitude,latitude,...,region.value,adminregion.id,adminregion.iso2code,adminregion.value,incomeLevel.id,incomeLevel.iso2code,incomeLevel.value,lendingType.id,lendingType.iso2code,lendingType.value
0,2025,Afghanistan,NaN,NaN,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,...,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
1,2024,Afghanistan,66.289,NaN,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,...,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
2,2023,Afghanistan,66.035,1983.812620,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,...,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
3,2022,Afghanistan,65.617,1981.710168,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,...,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
4,2021,Afghanistan,60.417,2144.166570,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,...,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17452,1964,Zimbabwe,55.431,NaN,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,...,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend
17453,1963,Zimbabwe,54.942,NaN,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,...,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend
17454,1962,Zimbabwe,54.453,NaN,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,...,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend
17455,1961,Zimbabwe,53.966,NaN,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,...,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend
17456,1960,Zimbabwe,53.492,NaN,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,...,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend

In [26]:
country_gdp_life = country_gdp_life.loc[country_gdp_life['region.id'] != 'NA']
country_gdp_life

,Year,Country,Life Expectancy,GDP Per Capita,id,iso2Code,name,capitalCity,longitude,latitude,...,region.value,adminregion.id,adminregion.iso2code,adminregion.value,incomeLevel.id,incomeLevel.iso2code,incomeLevel.value,lendingType.id,lendingType.iso2code,lendingType.value
0,2025,Afghanistan,NaN,NaN,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,...,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
1,2024,Afghanistan,66.289,NaN,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,...,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
2,2023,Afghanistan,66.035,1983.812620,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,...,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
3,2022,Afghanistan,65.617,1981.710168,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,...,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
4,2021,Afghanistan,60.417,2144.166570,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,...,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17452,1964,Zimbabwe,55.431,NaN,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,...,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend
17453,1963,Zimbabwe,54.942,NaN,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,...,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend
17454,1962,Zimbabwe,54.453,NaN,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,...,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend
17455,1961,Zimbabwe,53.966,NaN,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,...,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend
17456,1960,Zimbabwe,53.492,NaN,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,...,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend

**Bonus Questions:** After doing a basic request to get all records, you can attempt these exercises to get additional practice using query parameters.

1. Adjust your request so that it returns data just for the United States.

2. Adjust your request so that it returns data just for the United States for the year 2021.

3. Adjust your request so that it returns data just for the United States for the years 2000 through 2021.

4. Adjust your request so that it returns data for the United States and Canada for the years 2000 through 2021.

5. If you haven't already done so and you would like to get some additional practice using loops, use the page parameter in order to pull all records. 
Do not change the value of the per_page parameter. You will likely need to utilize a loop of some kind in order to pull all records.

6. The endpoint "http://api.worldbank.org/v2/indicator" will return information about all available indicators. 
See [Indicator API Queries](https://datahelpdesk.worldbank.org/knowledgebase/articles/898599-indicator-api-queries). 
Use this endpoint to find the code for the "Public Expenditure on Education (% GDP)" indicator.

In [27]:
country_gdp_life.loc[country_gdp_life['Country']== 'United States']

,Year,Country,Life Expectancy,GDP Per Capita,id,iso2Code,name,capitalCity,longitude,latitude,...,region.value,adminregion.id,adminregion.iso2code,adminregion.value,incomeLevel.id,incomeLevel.iso2code,incomeLevel.value,lendingType.id,lendingType.iso2code,lendingType.value
16599,2025,United States,NaN,NaN,USA,US,United States,Washington D.C.,-77.032,38.8895,...,North America,,,,HIC,XD,High income,LNX,XX,Not classified
16600,2024,United States,78.890244,75489.266433,USA,US,United States,Washington D.C.,-77.032,38.8895,...,North America,,,,HIC,XD,High income,LNX,XX,Not classified
16601,2023,United States,78.385366,74158.716416,USA,US,United States,Washington D.C.,-77.032,38.8895,...,North America,,,,HIC,XD,High income,LNX,XX,Not classified
16602,2022,United States,77.434146,72679.257540,USA,US,United States,Washington D.C.,-77.032,38.8895,...,North America,,,,HIC,XD,High income,LNX,XX,Not classified
16603,2021,United States,76.329268,71307.401728,USA,US,United States,Washington D.C.,-77.032,38.8895,...,North America,,,,HIC,XD,High income,LNX,XX,Not classified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16660,1964,United States,70.165854,NaN,USA,US,United States,Washington D.C.,-77.032,38.8895,...,North America,,,,HIC,XD,High income,LNX,XX,Not classified
16661,1963,United States,69.917073,NaN,USA,US,United States,Washington D.C.,-77.032,38.8895,...,North America,,,,HIC,XD,High income,LNX,XX,Not classified
16662,1962,United States,70.119512,NaN,USA,US,United States,Washington D.C.,-77.032,38.8895,...,North America,,,,HIC,XD,High income,LNX,XX,Not classified
16663,1961,United States,70.270732,NaN,USA,US,United States,Washington D.C.,-77.032,38.8895,...,North America,,,,HIC,XD,High income,LNX,XX,Not classified
16664,1960,United States,69.770732,NaN,USA,US,United States,Washington D.C.,-77.032,38.8895,...,North America,,,,HIC,XD,High income,LNX,XX,Not classified